[General]
Aur_Tool_Name=paru
Backend=alpm
Distro_RSS_Url=https://archlinux.org/feeds/news/
Instant_Search=true
PackageList_Ordered_Col=0
PackageList_Sort_Order=0
Package_Download_Size_Column_Width=120
Package_Icon_Column_Width=31
Package_Name_Column_Width=400
Package_Repository_Column_Width=150
Package_Version_Column_Width=260
Search_Method=0
Show_Groups_Panel=false
Splitter_Horizontal_State=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xc0\0\0\0\xf6\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
Use_Default_App_Icon=true
Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x2\xb5\0\0\x2\x91\0\0\0\0\0\0\0\0\0\0\x2\x35\0\0\x1\x42\0\0\0\0\x2\0\0\0\x5\0\0\0\0\0\0\0\0\0\0\0\x2\xb5\0\0\x2\x91)
