-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        active_opacity = 1.0,
        blur = {
            enabled = false,
        },
        dim_strength = 0.02,
        inactive_opacity = 0.95,
    },
})
