-- ######## Window rules ########

-- Disable blur for xwayland context menus
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^()$",
        title = "^()$",
    },
    no_blur = true,
})

-- Disable blur for every window
hl.window_rule({
    match = {
        class = ".*",
    },
    no_blur = true,
})

-- Floating
hl.window_rule({
    match = {
        title = "^(Open File)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Select a File)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Choose wallpaper)(.*)$",
    },
    center = true,
    float = true,
    size = "(monitor_w*.60) (monitor_h*.65)",
})

hl.window_rule({
    match = {
        title = "^(Open Folder)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Save As)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Library)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(File Upload)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(.*)(wants to save)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(.*)(wants to open)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        class = "^(blueberry\\.py)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(guifetch)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
    size = "(monitor_w*.45) (monitor_h*.45)",
    center = true,
})

hl.window_rule({
    match = {
        class = "^(org.pulseaudio.pavucontrol)$",
    },
    float = true,
    size = "(monitor_w*.45) (monitor_h*.45)",
    center = true,
})

hl.window_rule({
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true,
    size = "(monitor_w*.45) (monitor_h*.45)",
    center = true,
})

hl.window_rule({
    match = {
        class = ".*plasmawindowed.*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "kcm_.*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = ".*bluedevilwizard",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = ".*Welcome",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(illogical-impulse Settings)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = ".*Shell conflicts.*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "org.freedesktop.impl.portal.desktop.kde",
    },
    float = true,
    size = "(monitor_w*.60) (monitor_h*.65)",
})

hl.window_rule({
    match = {
        class = "^(Zotero)$",
    },
    float = true,
    size = "(monitor_w*.45) (monitor_h*.45)",
})

-- Move
-- kde-material-you-colors spawns a window when changing dark/light theme. This is to make sure it doesn't interfere at all.
hl.window_rule({
    match = {
        class = "^(plasma-changeicons)$",
    },
    float = true,
    no_initial_focus = true,
    move = "999999 999999",
})

-- stupid dolphin copy
hl.window_rule({
    match = {
        title = "^(Copying — Dolphin)$",
    },
    move = "40 80",
})

-- Tiling
hl.window_rule({
    match = {
        class = "^dev\\.warp\\.Warp$",
    },
    float = false,
})

-- Picture-in-Picture
hl.window_rule({
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
    },
    float = true,
    keep_aspect_ratio = true,
    move = "(monitor_w*.73) (monitor_h*.72)",
    size = "(monitor_w*.25) (monitor_h*.25)",
    float = true,
    pin = true,
})

-- --- Tearing ---
hl.window_rule({
    match = {
        title = ".*\\.exe",
    },
    immediate = true,
})

hl.window_rule({
    match = {
        title = ".*minecraft.*",
    },
    immediate = true,
})

hl.window_rule({
    match = {
        class = "^(steam_app).*",
    },
    immediate = true,
})

-- Fix Jetbrain IDEs focus/rerendering problem
hl.window_rule({
    match = {
        class = "^jetbrains-.*$",
        float = 1,
        title = "^$|^\\s$|^win\\d+$",
    },
    no_initial_focus = true,
})

-- No shadow for tiled windows (matches windows that are not floating).
hl.window_rule({
    match = {
        float = 0,
    },
    no_shadow = true,
})

-- ######## Workspace rules ########
hl.workspace_rule({
    workspace = "special:special",
    gaps_out = 30,
})

-- ######## Layer rules ########
hl.layer_rule({
    match = { namespace = "xray on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace .*"
})

-- layerrule = match:namespace .*, no_anim on
hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace walker"
    -- TODO: manual review — unmapped layer rule: "match:namespace selection"
    -- TODO: manual review — unmapped layer rule: "match:namespace overview"
    -- TODO: manual review — unmapped layer rule: "match:namespace anyrun"
    -- TODO: manual review — unmapped layer rule: "match:namespace indicator.*"
    -- TODO: manual review — unmapped layer rule: "match:namespace osk"
    -- TODO: manual review — unmapped layer rule: "match:namespace hyprpicker"
})

hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace noanim"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace gtk-layer-shell"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0" },
    -- TODO: manual review — unmapped layer rule: "match:namespace gtk-layer-shell"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace launcher"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.5" },
    -- TODO: manual review — unmapped layer rule: "match:namespace launcher"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace notifications"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.69" },
    -- TODO: manual review — unmapped layer rule: "match:namespace notifications"
})

-- TODO: manual review — malformed layerrule on line 103: match:namespace logout_dialog

-- ags
hl.layer_rule({
    match = { namespace = "animation slide left" },
    -- TODO: manual review — unmapped layer rule: "match:namespace sideleft.*"
})

hl.layer_rule({
    match = { namespace = "animation slide right" },
    -- TODO: manual review — unmapped layer rule: "match:namespace sideright.*"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace session[0-9]*"
    -- TODO: manual review — unmapped layer rule: "match:namespace bar[0-9]*"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.6" },
    -- TODO: manual review — unmapped layer rule: "match:namespace bar[0-9]*"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace barcorner.*"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.6" },
    -- TODO: manual review — unmapped layer rule: "match:namespace barcorner.*"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace dock[0-9]*"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.6" },
    -- TODO: manual review — unmapped layer rule: "match:namespace dock[0-9]*"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace indicator.*"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.6" },
    -- TODO: manual review — unmapped layer rule: "match:namespace indicator.*"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace overview[0-9]*"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.6" },
    -- TODO: manual review — unmapped layer rule: "match:namespace overview[0-9]*"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace cheatsheet[0-9]*"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.6" },
    -- TODO: manual review — unmapped layer rule: "match:namespace cheatsheet[0-9]*"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace sideright[0-9]*"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.6" },
    -- TODO: manual review — unmapped layer rule: "match:namespace sideright[0-9]*"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace sideleft[0-9]*"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.6" },
    -- TODO: manual review — unmapped layer rule: "match:namespace sideleft[0-9]*"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace indicator.*"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.6" },
    -- TODO: manual review — unmapped layer rule: "match:namespace indicator.*"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace osk[0-9]*"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.6" },
    -- TODO: manual review — unmapped layer rule: "match:namespace osk[0-9]*"
})

-- Quickshell
-- Quickshell: illogical-impulse
hl.layer_rule({
    match = { namespace = "blur_popups on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:.*"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:.*"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.79" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:.*"
})

hl.layer_rule({
    match = { namespace = "animation slide" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:bar"
})

hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:actionCenter"
})

hl.layer_rule({
    match = { namespace = "animation slide bottom" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:cheatsheet"
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:dock"
})

hl.layer_rule({
    match = { namespace = "animation popin 120%" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:screenCorners"
})

hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:lockWindowPusher"
})

hl.layer_rule({
    match = { namespace = "animation fade" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:notificationPopup"
})

hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:overlay"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 1" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:overlay"
})

hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:overview"
})

hl.layer_rule({
    match = { namespace = "animation slide bottom" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:osk"
})

hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:polkit"
})

hl.layer_rule({
    match = { namespace = "xray off" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:popup"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 1" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:popup"
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:mediaControls"
})

hl.layer_rule({
    match = { namespace = "animation slide" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:reloadPopup"
})

hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:regionSelector"
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:screenshot"
})

hl.layer_rule({
    match = { namespace = "blur on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:session"
})

hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:session"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:session"
})

hl.layer_rule({
    match = { namespace = "animation slide right" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:sidebarRight"
})

hl.layer_rule({
    match = { namespace = "animation slide left" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:sidebarLeft"
})

hl.layer_rule({
    match = { namespace = "animation slide" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:verticalBar"
})

hl.layer_rule({
    match = { namespace = "order -1" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:osk"
})

-- Quickshell: waffles
hl.layer_rule({
    match = { namespace = "animation slide top" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:wallpaperSelector"
})

hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:wNotificationCenter"
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:wOnScreenDisplay"
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:wStartMenu"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:wTaskView"
})

hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:wTaskView"
})

-- Launchers need to be FAST
hl.layer_rule({
    match = { namespace = "no_anim on" },
    -- TODO: manual review — unmapped layer rule: "match:namespace gtk4-layer-shell"
})

