-- Generated by HyprMod

-- Settings
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'noise = 0.01' has no enclosing section
-- TODO: manual review — top-level key 'color_inactive = 0xff000000' has no enclosing section
-- TODO: manual review — top-level key 'enabled = false' has no enclosing section
-- TODO: manual review — top-level key 'render_power = 4' has no enclosing section

hl.monitor({
    output = "HDMI-A-3",
    mode = "1920x1080@60.00Hz",
    position = "0x10",
    scale = "1",
    cm = "srgb",
})

hl.config({
    cursor = {
        hide_on_touch = false,
    },
    -- TODO: manual review — unexpected token after 'decoration'
    decoration = {
        dim_inactive = true,
        dim_strength = 0.12,
    },
    -- TODO: manual review — unexpected token after 'decoration'
    -- TODO: manual review — unexpected token after 'decoration'
    -- TODO: manual review — unexpected token after 'decoration'
    general = {
        allow_tearing = true,
        border_size = 3,
        col = {
            active_border = "0xff8ff0a4 0xff1111ee 45deg",
            inactive_border = "0xaa595959 9deg",
        },
        layout = "master",
    },
    input = {
        accel_profile = "",
        kb_layout = "dk",
        sensitivity = 0.15,
    },
    master = {
        allow_small_split = true,
        orientation = "center",
    },
    misc = {
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
        vrr = 1,
    },
    xwayland = {
        force_zero_scaling = true,
    },
    -- Monitors
})

