var config = {};

config.test = {"page": "https://webbrowsertools.com/timezone/"};

config.addon = {
  set state (val) {app.storage.write("state", val)},
  get state () {return app.storage.read("state") !== undefined ? app.storage.read("state") : "ON"}
};

config.welcome = {
  set lastupdate (val) {app.storage.write("lastupdate", val)},
  get lastupdate () {return app.storage.read("lastupdate") !== undefined ? app.storage.read("lastupdate") : 0}
};

config.options = {
  "timezone": {
    set name (val) {app.storage.write("timezone-name", val)},
    set index (val) {app.storage.write("timezone-index", val)},
    set value (val) {app.storage.write("timezone-value", val)},
    get value () {return app.storage.read("timezone-value") !== undefined ? app.storage.read("timezone-value") : 0},
    get index () {return app.storage.read("timezone-index") !== undefined ? app.storage.read("timezone-index") : 150},
    get name () {return app.storage.read("timezone-name") !== undefined ? app.storage.read("timezone-name") : "Etc/Greenwich"}
  },
  "extra": {
    set stealthStackTrace (val) {app.storage.write("stealthStackTrace", val)},
    set dateParsingStealth (val) {app.storage.write("dateParsingStealth", val)},
    set crossRealmProtection (val) {app.storage.write("crossRealmProtection", val)},
    set intlConsistencyPatch (val) {app.storage.write("intlConsistencyPatch", val)},
    set timezoneNameAlignment (val) {app.storage.write("timezoneNameAlignment", val)},
    set workerContextProtection (val) {app.storage.write("workerContextProtection", val)},
    set nativeFunctionIntegrity (val) {app.storage.write("nativeFunctionIntegrity", val)},
    //
    get stealthStackTrace () {return app.storage.read("stealthStackTrace") !== undefined ? app.storage.read("stealthStackTrace") : false},
    get dateParsingStealth () {return app.storage.read("dateParsingStealth") !== undefined ? app.storage.read("dateParsingStealth") : false},
    get crossRealmProtection () {return app.storage.read("crossRealmProtection") !== undefined ? app.storage.read("crossRealmProtection") : false},
    get intlConsistencyPatch () {return app.storage.read("intlConsistencyPatch") !== undefined ? app.storage.read("intlConsistencyPatch") : false},
    get timezoneNameAlignment () {return app.storage.read("timezoneNameAlignment") !== undefined ? app.storage.read("timezoneNameAlignment") : false},
    get workerContextProtection () {return app.storage.read("workerContextProtection") !== undefined ? app.storage.read("workerContextProtection") : false},
    get nativeFunctionIntegrity () {return app.storage.read("nativeFunctionIntegrity") !== undefined ? app.storage.read("nativeFunctionIntegrity") : false}
  }
};

config.default = {
  "list": [
    {"name": "Pacific/Kiritimati", "offset": 840, "index": 0},
    {"name": "Pacific/Apia", "offset": 840, "index": 1},
    {"name": "Pacific/Enderbury", "offset": 780, "index": 2},
    {"name": "Pacific/Tongatapu", "offset": 780, "index": 3},
    {"name": "Pacific/Fakaofo", "offset": 780, "index": 4},
    {"name": "Pacific/Auckland", "offset": 780, "index": 5},
    {"name": "Pacific/Fiji", "offset": 780, "index": 6},
    {"name": "Pacific/Nauru", "offset": 720, "index": 7},
    {"name": "Pacific/Funafuti", "offset": 720, "index": 8},
    {"name": "Pacific/Tarawa", "offset": 720, "index": 9},
    {"name": "Pacific/Wake", "offset": 720, "index": 10},
    {"name": "Asia/Kamchatka", "offset": 720, "index": 11},
    {"name": "Pacific/Kwajalein", "offset": 720, "index": 12},
    {"name": "Pacific/Majuro", "offset": 720, "index": 13},
    {"name": "Pacific/Wallis", "offset": 720, "index": 14},
    {"name": "Australia/Sydney", "offset": 660, "index": 15},
    {"name": "Pacific/Kosrae", "offset": 660, "index": 16},
    {"name": "Pacific/Guadalcanal", "offset": 660, "index": 17},
    {"name": "Pacific/Efate", "offset": 660, "index": 18},
    {"name": "Pacific/Pohnpei", "offset": 660, "index": 19},
    {"name": "Pacific/Noumea", "offset": 660, "index": 20},
    {"name": "Australia/Hobart", "offset": 660, "index": 21},
    {"name": "Pacific/Norfolk", "offset": 660, "index": 22},
    {"name": "Australia/Adelaide", "offset": 630, "index": 23},
    {"name": "Pacific/Chuuk", "offset": 600, "index": 24},
    {"name": "Asia/Vladivostok", "offset": 600, "index": 25},
    {"name": "Asia/Magadan", "offset": 600, "index": 26},
    {"name": "Antarctica/DumontDUrville", "offset": 600, "index": 27},
    {"name": "Pacific/Guam", "offset": 600, "index": 28},
    {"name": "Pacific/Port_Moresby", "offset": 600, "index": 29},
    {"name": "Australia/Brisbane", "offset": 600, "index": 30},
    {"name": "Australia/Darwin", "offset": 570, "index": 31},
    {"name": "Asia/Yakutsk", "offset": 540, "index": 32},
    {"name": "Asia/Tokyo", "offset": 540, "index": 33},
    {"name": "Asia/Seoul", "offset": 540, "index": 34},
    {"name": "Asia/Jayapura", "offset": 540, "index": 35},
    {"name": "Asia/Dili", "offset": 540, "index": 36},
    {"name": "Pacific/Palau", "offset": 540, "index": 37},
    {"name": "Asia/Pyongyang", "offset": 510, "index": 38},
    {"name": "Asia/Choibalsan", "offset": 480, "index": 39},
    {"name": "Asia/Taipei", "offset": 480, "index": 40},
    {"name": "Asia/Singapore", "offset": 480, "index": 41},
    {"name": "Australia/Perth", "offset": 480, "index": 42},
    {"name": "Asia/Manila", "offset": 480, "index": 43},
    {"name": "Asia/Makassar", "offset": 480, "index": 44},
    {"name": "Asia/Macau", "offset": 480, "index": 45},
    {"name": "Asia/Kuala_Lumpur", "offset": 480, "index": 46},
    {"name": "Asia/Irkutsk", "offset": 480, "index": 47},
    {"name": "Asia/Hong_Kong", "offset": 480, "index": 48},
    {"name": "Asia/Ulaanbaatar", "offset": 480, "index": 49},
    {"name": "Asia/Brunei", "offset": 480, "index": 50},
    {"name": "Antarctica/Casey", "offset": 480, "index": 51},
    {"name": "Asia/Shanghai", "offset": 480, "index": 52},
    {"name": "Indian/Christmas", "offset": 420, "index": 53},
    {"name": "Asia/Saigon", "offset": 420, "index": 54},
    {"name": "Asia/Krasnoyarsk", "offset": 420, "index": 55},
    {"name": "Asia/Jakarta", "offset": 420, "index": 56},
    {"name": "Asia/Hovd", "offset": 420, "index": 57},
    {"name": "Asia/Bangkok", "offset": 420, "index": 58},
    {"name": "Antarctica/Davis", "offset": 420, "index": 59},
    {"name": "Indian/Cocos", "offset": 390, "index": 60},
    {"name": "Asia/Rangoon", "offset": 390, "index": 61},
    {"name": "Indian/Chagos", "offset": 360, "index": 62},
    {"name": "Asia/Thimphu", "offset": 360, "index": 63},
    {"name": "Asia/Dhaka", "offset": 360, "index": 64},
    {"name": "Asia/Bishkek", "offset": 360, "index": 65},
    {"name": "Asia/Almaty", "offset": 360, "index": 66},
    {"name": "Antarctica/Vostok", "offset": 360, "index": 67},
    {"name": "Asia/Omsk", "offset": 360, "index": 68},
    {"name": "Asia/Katmandu", "offset": 345, "index": 69},
    {"name": "Asia/Colombo", "offset": 330, "index": 70},
    {"name": "Asia/Calcutta", "offset": 330, "index": 71},
    {"name": "Indian/Kerguelen", "offset": 300, "index": 72},
    {"name": "Asia/Yekaterinburg", "offset": 300, "index": 73},
    {"name": "Asia/Tashkent", "offset": 300, "index": 74},
    {"name": "Asia/Karachi", "offset": 300, "index": 75},
    {"name": "Asia/Dushanbe", "offset": 300, "index": 76},
    {"name": "Asia/Ashgabat", "offset": 300, "index": 77},
    {"name": "Asia/Aqtobe", "offset": 300, "index": 78},
    {"name": "Asia/Aqtau", "offset": 300, "index": 79},
    {"name": "Indian/Maldives", "offset": 300, "index": 80},
    {"name": "Antarctica/Mawson", "offset": 300, "index": 81},
    {"name": "Asia/Kabul", "offset": 270, "index": 82},
    {"name": "Indian/Mauritius", "offset": 240, "index": 83},
    {"name": "Indian/Mahe", "offset": 240, "index": 84},
    {"name": "Europe/Samara", "offset": 240, "index": 85},
    {"name": "Indian/Reunion", "offset": 240, "index": 86},
    {"name": "Asia/Tbilisi", "offset": 240, "index": 87},
    {"name": "Asia/Dubai", "offset": 240, "index": 88},
    {"name": "Asia/Baku", "offset": 240, "index": 89},
    {"name": "Asia/Yerevan", "offset": 240, "index": 90},
    {"name": "Asia/Tehran", "offset": 210, "index": 91},
    {"name": "Europe/Moscow", "offset": 180, "index": 92},
    {"name": "Europe/Minsk", "offset": 180, "index": 93},
    {"name": "Asia/Riyadh", "offset": 180, "index": 94},
    {"name": "Asia/Qatar", "offset": 180, "index": 95},
    {"name": "Asia/Baghdad", "offset": 180, "index": 96},
    {"name": "Antarctica/Syowa", "offset": 180, "index": 97},
    {"name": "Africa/Nairobi", "offset": 180, "index": 98},
    {"name": "Africa/Khartoum", "offset": 180, "index": 99},
    {"name": "Asia/Jerusalem", "offset": 120, "index": 100},
    {"name": "Europe/Vilnius", "offset": 120, "index": 101},
    {"name": "Europe/Tallinn", "offset": 120, "index": 102},
    {"name": "Africa/Cairo", "offset": 120, "index": 103},
    {"name": "Africa/Johannesburg", "offset": 120, "index": 104},
    {"name": "Africa/Maputo", "offset": 120, "index": 105},
    {"name": "Africa/Tripoli", "offset": 120, "index": 106},
    {"name": "Asia/Amman", "offset": 120, "index": 107},
    {"name": "Asia/Beirut", "offset": 120, "index": 108},
    {"name": "Asia/Damascus", "offset": 120, "index": 109},
    {"name": "Asia/Gaza", "offset": 120, "index": 110},
    {"name": "Africa/Windhoek", "offset": 120, "index": 111},
    {"name": "Asia/Nicosia", "offset": 120, "index": 112},
    {"name": "Europe/Athens", "offset": 120, "index": 113},
    {"name": "Europe/Bucharest", "offset": 120, "index": 114},
    {"name": "Europe/Chisinau", "offset": 120, "index": 115},
    {"name": "Europe/Helsinki", "offset": 120, "index": 116},
    {"name": "Europe/Istanbul", "offset": 120, "index": 117},
    {"name": "Europe/Kaliningrad", "offset": 120, "index": 118},
    {"name": "Europe/Kiev", "offset": 120, "index": 119},
    {"name": "Europe/Riga", "offset": 120, "index": 120},
    {"name": "Europe/Sofia", "offset": 120, "index": 121},
    {"name": "Europe/Prague", "offset": 60, "index": 122},
    {"name": "Europe/Rome", "offset": 60, "index": 123},
    {"name": "Europe/Stockholm", "offset": 60, "index": 124},
    {"name": "Africa/Algiers", "offset": 60, "index": 125},
    {"name": "Europe/Vienna", "offset": 60, "index": 126},
    {"name": "Europe/Warsaw", "offset": 60, "index": 127},
    {"name": "Europe/Zurich", "offset": 60, "index": 128},
    {"name": "Africa/Ceuta", "offset": 60, "index": 129},
    {"name": "Africa/Lagos", "offset": 60, "index": 130},
    {"name": "Africa/Ndjamena", "offset": 60, "index": 131},
    {"name": "Africa/Tunis", "offset": 60, "index": 132},
    {"name": "Europe/Tirane", "offset": 60, "index": 133},
    {"name": "Europe/Amsterdam", "offset": 60, "index": 134},
    {"name": "Europe/Andorra", "offset": 60, "index": 135},
    {"name": "Europe/Belgrade", "offset": 60, "index": 136},
    {"name": "Europe/Berlin", "offset": 60, "index": 137},
    {"name": "Europe/Brussels", "offset": 60, "index": 138},
    {"name": "Europe/Budapest", "offset": 60, "index": 139},
    {"name": "Europe/Copenhagen", "offset": 60, "index": 140},
    {"name": "Europe/Gibraltar", "offset": 60, "index": 141},
    {"name": "Europe/Luxembourg", "offset": 60, "index": 142},
    {"name": "Europe/Madrid", "offset": 60, "index": 143},
    {"name": "Europe/Malta", "offset": 60, "index": 144},
    {"name": "Europe/Monaco", "offset": 60, "index": 145},
    {"name": "Europe/Oslo", "offset": 60, "index": 146},
    {"name": "Europe/Paris", "offset": 60, "index": 147},
    {"name": "Africa/Bissau", "offset": 0, "index": 148},
    {"name": "Europe/London", "offset": 0, "index": 149},
    {"name": "Etc/Greenwich", "offset": 0, "index": 150},
    {"name": "Atlantic/Reykjavik", "offset": 0, "index": 151},
    {"name": "Atlantic/Faroe", "offset": 0, "index": 152},
    {"name": "Atlantic/Canary", "offset": 0, "index": 153},
    {"name": "America/Danmarkshavn", "offset": 0, "index": 154},
    {"name": "Africa/Monrovia", "offset": 0, "index": 155},
    {"name": "Africa/El_Aaiun", "offset": 0, "index": 156},
    {"name": "Africa/Casablanca", "offset": 0, "index": 157},
    {"name": "Europe/Dublin", "offset": 0, "index": 158},
    {"name": "Africa/Accra", "offset": 0, "index": 159},
    {"name": "Africa/Abidjan", "offset": 0, "index": 160},
    {"name": "Europe/Lisbon", "offset": 0, "index": 161},
    {"name": "Atlantic/Cape_Verde", "offset": -60, "index": 162},
    {"name": "Atlantic/Azores", "offset": -60, "index": 163},
    {"name": "America/Scoresbysund", "offset": -60, "index": 164},
    {"name": "Atlantic/South_Georgia", "offset": -120, "index": 165},
    {"name": "America/Noronha", "offset": -120, "index": 166},
    {"name": "America/Sao_Paulo", "offset": -120, "index": 167},
    {"name": "America/St_Johns", "offset": -150, "index": 168},
    {"name": "Antarctica/Palmer", "offset": -180, "index": 169},
    {"name": "America/Cuiaba", "offset": -180, "index": 170},
    {"name": "America/Santiago", "offset": -180, "index": 171},
    {"name": "America/Recife", "offset": -180, "index": 172},
    {"name": "America/Paramaribo", "offset": -180, "index": 173},
    {"name": "America/Montevideo", "offset": -180, "index": 174},
    {"name": "America/Miquelon", "offset": -180, "index": 175},
    {"name": "America/Maceio", "offset": -180, "index": 176},
    {"name": "America/Godthab", "offset": -180, "index": 177},
    {"name": "America/Fortaleza", "offset": -180, "index": 178},
    {"name": "America/Cayenne", "offset": -180, "index": 179},
    {"name": "America/Belem", "offset": -180, "index": 180},
    {"name": "America/Bahia", "offset": -180, "index": 181},
    {"name": "America/Argentina/Buenos_Aires", "offset": -180, "index": 182},
    {"name": "America/Araguaina", "offset": -180, "index": 183},
    {"name": "Atlantic/Stanley", "offset": -180, "index": 184},
    {"name": "America/Asuncion", "offset": -180, "index": 185},
    {"name": "America/Campo_Grande", "offset": -180, "index": 186},
    {"name": "Antarctica/Rothera", "offset": -180, "index": 187},
    {"name": "America/Caracas", "offset": -210, "index": 188},
    {"name": "America/Curacao", "offset": -240, "index": 189},
    {"name": "America/Martinique", "offset": -240, "index": 190},
    {"name": "America/Manaus", "offset": -240, "index": 191},
    {"name": "America/La_Paz", "offset": -240, "index": 192},
    {"name": "America/Halifax", "offset": -240, "index": 193},
    {"name": "America/Guyana", "offset": -240, "index": 194},
    {"name": "America/Grand_Turk", "offset": -240, "index": 195},
    {"name": "America/Port_of_Spain", "offset": -240, "index": 196},
    {"name": "America/Santo_Domingo", "offset": -240, "index": 197},
    {"name": "America/Thule", "offset": -240, "index": 198},
    {"name": "America/Boa_Vista", "offset": -240, "index": 199},
    {"name": "America/Barbados", "offset": -240, "index": 200},
    {"name": "Atlantic/Bermuda", "offset": -240, "index": 201},
    {"name": "America/Puerto_Rico", "offset": -240, "index": 202},
    {"name": "America/Porto_Velho", "offset": -240, "index": 203},
    {"name": "Pacific/Easter", "offset": -300, "index": 204},
    {"name": "America/Toronto", "offset": -300, "index": 205},
    {"name": "America/Rio_Branco", "offset": -300, "index": 206},
    {"name": "America/Port-au-Prince", "offset": -300, "index": 207},
    {"name": "America/Panama", "offset": -300, "index": 208},
    {"name": "America/New_York", "offset": -300, "index": 209},
    {"name": "America/Nassau", "offset": -300, "index": 210},
    {"name": "America/Lima", "offset": -300, "index": 211},
    {"name": "America/Jamaica", "offset": -300, "index": 212},
    {"name": "America/Iqaluit", "offset": -300, "index": 213},
    {"name": "America/Havana", "offset": -300, "index": 214},
    {"name": "America/Guayaquil", "offset": -300, "index": 215},
    {"name": "America/Cayman", "offset": -300, "index": 216},
    {"name": "America/Cancun", "offset": -300, "index": 217},
    {"name": "America/Bogota", "offset": -300, "index": 218},
    {"name": "America/Guatemala", "offset": -360, "index": 219},
    {"name": "Pacific/Galapagos", "offset": -360, "index": 220},
    {"name": "America/Regina", "offset": -360, "index": 221},
    {"name": "America/Mexico_City", "offset": -360, "index": 222},
    {"name": "America/Managua", "offset": -360, "index": 223},
    {"name": "America/Tegucigalpa", "offset": -360, "index": 224},
    {"name": "America/El_Salvador", "offset": -360, "index": 225},
    {"name": "America/Costa_Rica", "offset": -360, "index": 226},
    {"name": "America/Chicago", "offset": -360, "index": 227},
    {"name": "America/Belize", "offset": -360, "index": 228},
    {"name": "America/Winnipeg", "offset": -360, "index": 229},
    {"name": "America/Yellowknife", "offset": -420, "index": 230},
    {"name": "America/Phoenix", "offset": -420, "index": 231},
    {"name": "America/Mazatlan", "offset": -420, "index": 232},
    {"name": "America/Hermosillo", "offset": -420, "index": 233},
    {"name": "America/Edmonton", "offset": -420, "index": 234},
    {"name": "America/Denver", "offset": -420, "index": 235},
    {"name": "America/Dawson_Creek", "offset": -420, "index": 236},
    {"name": "Pacific/Pitcairn", "offset": -480, "index": 237},
    {"name": "America/Vancouver", "offset": -480, "index": 238},
    {"name": "America/Tijuana", "offset": -480, "index": 239},
    {"name": "America/Los_Angeles", "offset": -480, "index": 240},
    {"name": "America/Whitehorse", "offset": -480, "index": 241},
    {"name": "Pacific/Marquesas", "offset": -510, "index": 242},
    {"name": "America/Anchorage", "offset": -540, "index": 243},
    {"name": "Pacific/Gambier", "offset": -540, "index": 244},
    {"name": "Pacific/Tahiti", "offset": -600, "index": 245},
    {"name": "Pacific/Rarotonga", "offset": -600, "index": 246},
    {"name": "Pacific/Honolulu", "offset": -600, "index": 247},
    {"name": "Pacific/Pago_Pago", "offset": -660, "index": 248},
    {"name": "Pacific/Niue", "offset": -660, "index": 249}
  ]
};

config.get = function (name) {
  return name.split('.').reduce(function (p, c) {
    return p[c];
  }, config);
};

config.set = function (name, value) {
  const _set = function (name, value, scope) {
    name = name.split('.');
    if (name.length > 1) {
      _set.call((scope || this)[name.shift()], name.join('.'), value);
    } else {
      this[name[0]] = value;
    }
  }
  /*  */
  _set(name, value, config);
};
